name: Code tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install system packages
        run: sudo apt-get install gcc ipmitool
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pytest pytest-cov
          pip install -r requirements.txt
      - name: Test with pytest pytest-cov
        run: |
          pytest --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
